[Deploy][Fix]
> linkedin-tl@1.0.0 build:ts
> tsc

src/Domain/Services/CQRS/FactoryCQRSDataSocialConnection.ts:91:58 - error TS2345: Argument of type '{ adapter: DataGraphFollowersStatisticsDAO; }' is not assignable to parameter of type '{ adapter: IDataGraphsDataDAO; logger: LoggerInterface; }'.
  Property 'logger' is missing in type '{ adapter: DataGraphFollowersStatisticsDAO; }' but required in type '{ adapter: IDataGraphsDataDAO; logger: LoggerInterface; }'.

 91           return new ServiceCQRSGraphFollowersStatistics({
                                                             ~
 92             adapter: new DataGraphFollowersStatisticsDAO({
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
 94             }),
    ~~~~~~~~~~~~~~~
 95           }).execute({
    ~~~~~~~~~~~

  src/Domain/Services/CQRS/ServiceCQRSGraphFollowersStatistics.ts:15:52
    15   constructor(args: { adapter: IDataGraphsDataDAO; logger: LoggerInterface }) {
                                                          ~~~~~~
    'logger' is declared here.

Found 1 error.